// src/lib/constants/locationData.ts

// ============================================================
// 1. COUNTRY LIST (Bangla)
// ============================================================
export const countryList = [
  "বাংলাদেশ",
  "সৌদি আরব",
  "সংযুক্ত আরব আমিরাত",
  "কাতার",
  "ওমান",
  "কুয়েত",
  "মালয়েশিয়া",
  "সিঙ্গাপুর",
  "মার্কিন যুক্তরাষ্ট্র",
  "যুক্তরাজ্য",
];

// ============================================================
// 2. ENGLISH LOCATION DATA (used as source to build Bangla lists)
//    These are the EXACT English names from your earlier file.
// ============================================================

// English divisions
export const divisionListEn = [
  "Barishal",
  "Chattogram",
  "Dhaka",
  "Khulna",
  "Mymensingh",
  "Rajshahi",
  "Rangpur",
  "Sylhet",
];

// English districts by division (all 64 districts)
export const districtByDivisionEn: Record<string, string[]> = {
  Barishal: ["Barguna", "Barishal", "Bhola", "Jhalokati", "Patuakhali", "Pirojpur"],
  Chattogram: [
    "Bandarban",
    "Brahmanbaria",
    "Chandpur",
    "Chattogram",
    "Cox's Bazar",
    "Cumilla",
    "Feni",
    "Khagrachhari",
    "Lakshmipur",
    "Noakhali",
    "Rangamati",
  ],
  Dhaka: [
    "Dhaka",
    "Faridpur",
    "Gazipur",
    "Gopalganj",
    "Kishoreganj",
    "Madaripur",
    "Manikganj",
    "Munshiganj",
    "Narayanganj",
    "Narsingdi",
    "Rajbari",
    "Shariatpur",
    "Tangail",
  ],
  Khulna: [
    "Bagerhat",
    "Chuadanga",
    "Jeshore",
    "Jhenaidah",
    "Khulna",
    "Kushtia",
    "Magura",
    "Meherpur",
    "Narail",
    "Satkhira",
  ],
  Mymensingh: ["Jamalpur", "Mymensingh", "Netrokona", "Sherpur"],
  Rajshahi: [
    "Bogra",
    "Joypurhat",
    "Naogaon",
    "Natore",
    "Nawabganj",
    "Pabna",
    "Rajshahi",
    "Sirajganj",
  ],
  Rangpur: [
    "Dinajpur",
    "Gaibandha",
    "Kurigram",
    "Lalmonirhat",
    "Nilphamari",
    "Panchagarh",
    "Rangpur",
    "Thakurgaon",
  ],
  Sylhet: ["Habiganj", "Moulvibazar", "Sunamganj", "Sylhet"],
};

// English thanas by district (all thanas – copied from your earlier file)
export const thanaByDistrictEn: Record<string, string[]> = {
  Barguna: ["Amtali", "Bamna", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"],
  Barishal: [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Gaurnadi",
    "Hizla",
    "Barishal Sadar",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],
  Bhola: ["Bhola Sadar", "Burhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan", "Manpura", "Tazumuddin"],
  Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  Patuakhali: [
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Patuakhali Sadar",
    "Rangabali",
  ],
  Pirojpur: ["Bhandaria", "Kaukhali", "Mathbaria", "Nazirpur", "Pirojpur Sadar", "Nesarabad (Swarupkathi)"],
  Bandarban: ["Ali Kadam", "Bandarban Sadar", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"],
  Brahmanbaria: ["Akhaura", "Bancharampur", "Brahmanbaria Sadar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail"],
  Chandpur: ["Chandpur Sadar", "Faridganj", "Haimchar", "Haziganj", "Kachua", "Matlab Dakshin", "Matlab Uttar", "Shahrasti"],
  Chattogram: [
    "Anwara",
    "Banshkhali",
    "Boalkhali",
    "Chandanaish",
    "Fatikchhari",
    "Hathazari",
    "Karnafuli",
    "Lohagara",
    "Mirsarai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
    "Bayezid Bostami",
    "Chandgaon",
    "Double Mooring",
    "Halishahar",
    "Kotwali",
    "Pahartali",
    "Panchlaish",
    "Patenga",
  ],
  "Cox's Bazar": ["Chakaria", "Cox's Bazar Sadar", "Kutubdia", "Maheshkhali", "Ramu", "Teknaf", "Ukhia", "Pekua"],
  Cumilla: [
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chouddagram",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Monohargonj",
    "Meghna",
    "Muradnagar",
    "Nangalkot",
    "Cumilla Adarsha Sadar",
    "Sadarsouth",
    "Titas",
  ],
  Feni: ["Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Parshuram", "Sonagazi"],
  Khagrachhari: [
    "Dighinala",
    "Khagrachhari Sadar",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh",
  ],
  Lakshmipur: ["Kamalnagar", "Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati"],
  Noakhali: [
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatiya",
    "Kabirhat",
    "Noakhali Sadar",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
  ],
  Rangamati: [
    "Baghaichhari",
    "Barkal",
    "Belaichhari",
    "Juraichhari",
    "Kaptai",
    "Kawkhali (Rangamati)",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
    "Rangamati Sadar",
  ],
  Dhaka: [
    "Adabor",
    "Badda",
    "Bangshal",
    "Cantonment",
    "Chakbazar",
    "Dhanmondi",
    "Gendaria",
    "Gulshan",
    "Hazaribagh",
    "Jatrabari",
    "Kafrul",
    "Kalabagan",
    "Kamrangirchar",
    "Khilgaon",
    "Khilkhet",
    "Kotwali",
    "Lalbagh",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "New Market",
    "Pallabi",
    "Paltan",
    "Ramna",
    "Rampura",
    "Sabujbagh",
    "Shah Ali",
    "Shahbagh",
    "Sher-e-Bangla Nagar",
    "Shyampur",
    "Sutrapur",
    "Tejgaon",
    "Tejgaon Industrial Area",
    "Turag",
    "Uttara",
    "Vatara",
    "Dhamrai",
    "Dohar",
    "Keraniganj",
    "Nawabganj",
    "Savar",
  ],
  Faridpur: ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrashen", "Faridpur Sadar", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"],
  Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur", "Tongi Sadar"],
  Gopalganj: ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
  Kishoreganj: [
    "Austagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  Madaripur: ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
  Manikganj: ["Daulatpur", "Ghior", "Harirampur", "Manikganj Sadar", "Saturia", "Shivalaya", "Singair"],
  Munshiganj: ["Gazaria", "Lohajang", "Munshiganj Sadar", "Sirajdikhan", "Sreenagar", "Tongibari"],
  Narayanganj: ["Narayanganj Sadar", "Araihazar", "Bandar", "Rupganj", "Sonargaon"],
  Narsingdi: ["Belabo", "Manohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"],
  Rajbari: ["Baliakandi", "Goalandaghat", "Kalukhali", "Pangsha", "Rajbari Sadar"],
  Shariatpur: ["Bhedarganj", "Damudya", "Gosairhat", "Jajira", "Naria", "Shariatpur Sadar", "Zanjira"],
  Tangail: [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
  ],
  Bagerhat: ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"],
  Chuadanga: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  Jeshore: ["Abhaynagar", "Bagherpara", "Chaugachha", "Jhikargachha", "Keshabpur", "Jashore Sadar", "Manirampur", "Sharsha"],
  Jhenaidah: ["Harinakunda", "Jhenaidah Sadar", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
  Khulna: [
    "Batiaghata",
    "Dacope",
    "Dumuria",
    "Dighalia",
    "Koyra",
    "Paikgachha",
    "Phultala",
    "Rupsha",
    "Terokhada",
    "Daulatpur",
    "Khalishpur",
    "Khan Jahan Ali",
    "Kotwali",
    "Sonadanga",
  ],
  Kushtia: ["Bheramara", "Daulatpur", "Kumarkhali", "Kushtia Sadar", "Khoksa", "Mirpur"],
  Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  Meherpur: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  Narail: ["Kalia", "Lohagara", "Narail Sadar"],
  Satkhira: ["Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Satkhira Sadar", "Shyamnagar", "Tala"],
  Jamalpur: ["Baksiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
  Mymensingh: [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gaffargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Mymensingh Sadar",
    "Muktagachha",
    "Nandail",
    "Phulpur",
    "Trishal",
    "Tara Khanda",
  ],
  Netrokona: [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Khaliajuri",
    "Kalmakanda",
    " Kendua",
    "Madan",
    "Mohanganj",
    "Netrokona Sadar",
    "Purbadhala",
  ],
  Sherpur: ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
  Bogra: [
    "Adamdighi",
    "Bogra Sadar",
    "Sherpur",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sonatola",
    "Shibganj",
  ],
  Joypurhat: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  Naogaon: [
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Manda",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  Natore: ["Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Natore Sadar", "Singra"],
  Nawabganj: ["Bholahat", "Gomastapur", "Nachole", "Nawabganj Sadar", "Shibganj"],
  Pabna: ["Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Pabna Sadar", "Santhia", "Sujanagar"],
  Rajshahi: [
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Paba",
    "Puthia",
    "Tanore",
    "Boalia",
    "Rajpara",
    "Shah Mokdum",
    "Motihar",
  ],
  Sirajganj: ["Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Rayganj", "Shahjadpur", "Sirajganj Sadar", "Tarash", "Ullapara"],
  Dinajpur: [
    "Dinajpur Sadar",
    "Birganj",
    "Bochaganj",
    "Chirirbandar",
    "Phulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
  ],
  Gaibandha: ["Gaibandha Sadar", "Fulchhari", "Gobindaganj", "Palashbari", "Saghata", "Sundarganj"],
  Kurigram: [
    "Kurigram Sadar",
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Phulbari",
    "Nageshwari",
    "Rajarhat",
    "Raomari",
    "Ulipur",
  ],
  Lalmonirhat: ["Lalmonirhat Sadar", "Aditmari", "Hatibandha", "Kaliganj", "Patgram"],
  Nilphamari: ["Nilphamari Sadar", "Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Saidpur"],
  Panchagarh: ["Panchagarh Sadar", "Atwari", "Boda", "Debiganj", "Tetulia"],
  Rangpur: ["Rangpur Sadar", "Badarganj", "Gangachara", "Kaunia", "Mithapukur", "Pirgacha", "Pirganj", "Taraganj"],
  Thakurgaon: ["Thakurgaon Sadar", "Baliadangi", "Haripur", "Pirganj", "Ranisankail"],
  Habiganj: ["Ajmiriganj", "Bahubal", "Baniachong", "Chunarughat", "Habiganj Sadar", "Lakhai", "Madhabpur", "Nabiganj"],
  Moulvibazar: ["Barlekha", "Juri", "Kamalganj", "Kulaura", "Moulvibazar Sadar", "Rajnagar", "Sreemangal"],
  Sunamganj: [
    "Bishwamvarpur",
    "Chhatak",
    "Dakshin Sunamganj",
    "Derai",
    "Dharampasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Shalla",
    "Sunamganj Sadar",
    "Tahirpur",
  ],
  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmaninagar",
    "Sylhet Sadar",
    "Zakiganj",
  ],
};

// ============================================================
// 3. COMPLETE TRANSLATION MAPS (English → Bangla)
//    These maps cover ALL divisions, districts, and thanas.
//    They are built from the translation tables you provided earlier.
// ============================================================

export const divisionBn: Record<string, string> = {
  Barishal: "বরিশাল",
  Chattogram: "চট্টগ্রাম",
  Dhaka: "ঢাকা",
  Khulna: "খুলনা",
  Mymensingh: "ময়মনসিংহ",
  Rajshahi: "রাজশাহী",
  Rangpur: "রংপুর",
  Sylhet: "সিলেট",
};

export const districtBn: Record<string, string> = {
  Barguna: "বরগুনা",
  Barishal: "বরিশাল",
  Bhola: "ভোলা",
  Jhalokati: "ঝালকাঠি",
  Patuakhali: "পটুয়াখালী",
  Pirojpur: "পিরোজপুর",
  Bandarban: "বান্দরবান",
  Brahmanbaria: "ব্রাহ্মণবাড়িয়া",
  Chandpur: "চাঁদপুর",
  Chattogram: "চট্টগ্রাম",
  "Cox's Bazar": "কক্সবাজার",
  Cumilla: "কুমিল্লা",
  Feni: "ফেনী",
  Khagrachhari: "খাগড়াছড়ি",
  Lakshmipur: "লক্ষ্মীপুর",
  Noakhali: "নোয়াখালী",
  Rangamati: "রাঙামাটি",
  Dhaka: "ঢাকা",
  Faridpur: "ফরিদপুর",
  Gazipur: "গাজীপুর",
  Gopalganj: "গোপালগঞ্জ",
  Kishoreganj: "কিশোরগঞ্জ",
  Madaripur: "মাদারীপুর",
  Manikganj: "মানিকগঞ্জ",
  Munshiganj: "মুন্সিগঞ্জ",
  Narayanganj: "নারায়ণগঞ্জ",
  Narsingdi: "নরসিংদী",
  Rajbari: "রাজবাড়ী",
  Shariatpur: "শরীয়তপুর",
  Tangail: "টাঙ্গাইল",
  Bagerhat: "বাগেরহাট",
  Chuadanga: "চুয়াডাঙ্গা",
  Jeshore: "যশোর",
  Jhenaidah: "ঝিনাইদহ",
  Khulna: "খুলনা",
  Kushtia: "কুষ্টিয়া",
  Magura: "মাগুরা",
  Meherpur: "মেহেরপুর",
  Narail: "নড়াইল",
  Satkhira: "সাতক্ষীরা",
  Jamalpur: "জামালপুর",
  Mymensingh: "ময়মনসিংহ",
  Netrokona: "নেত্রকোণা",
  Sherpur: "শেরপুর",
  Bogra: "বগুড়া",
  Joypurhat: "জয়পুরহাট",
  Naogaon: "নওগাঁ",
  Natore: "নাটোর",
  Nawabganj: "চাঁপাইনবাবগঞ্জ",
  Pabna: "পাবনা",
  Rajshahi: "রাজশাহী",
  Sirajganj: "সিরাজগঞ্জ",
  Dinajpur: "দিনাজপুর",
  Gaibandha: "গাইবান্ধা",
  Kurigram: "কুড়িগ্রাম",
  Lalmonirhat: "লালমনিরহাট",
  Nilphamari: "নীলফামারী",
  Panchagarh: "পঞ্চগড়",
  Rangpur: "রংপুর",
  Thakurgaon: "ঠাকুরগাঁও",
  Habiganj: "হবিগঞ্জ",
  Moulvibazar: "মৌলভীবাজার",
  Sunamganj: "সুনামগঞ্জ",
  Sylhet: "সিলেট",
};

// All thana translations (complete list from your previous file)
export const thanaBn: Record<string, string> = {
  // Barishal division
  Amtali: "আমতলী",
  Bamna: "বামনা",
  "Barguna Sadar": "বরগুনা সদর",
  Betagi: "বেতাগী",
  Patharghata: "পাথরঘাটা",
  Taltali: "তালতলী",
  Agailjhara: "আগৈলঝাড়া",
  Babuganj: "বাবুগঞ্জ",
  Bakerganj: "বাকেরগঞ্জ",
  Banaripara: "বানারীপাড়া",
  Gaurnadi: "গৌরনদী",
  Hizla: "হিজলা",
  "Barishal Sadar": "বরিশাল সদর",
  Mehendiganj: "মেহেন্দিগঞ্জ",
  Muladi: "মুলাদী",
  Wazirpur: "উজিরপুর",
  "Bhola Sadar": "ভোলা সদর",
  Burhanuddin: "বোরহানউদ্দিন",
  "Char Fasson": "চরফ্যাশন",
  Daulatkhan: "দৌলতখান",
  Lalmohan: "লালমোহন",
  Manpura: "মনপুরা",
  Tazumuddin: "তজুমদ্দিন",
  "Jhalokati Sadar": "ঝালকাঠি সদর",
  Kathalia: "কাঁঠালিয়া",
  Nalchity: "নলছিটি",
  Rajapur: "রাজাপুর",
  Bauphal: "বাউফল",
  Dashmina: "দশমিনা",
  Dumki: "দুমকি",
  Galachipa: "গলাচিপা",
  Kalapara: "কলাপাড়া",
  Mirzaganj: "মির্জাগঞ্জ",
  "Patuakhali Sadar": "পটুয়াখালী সদর",
  Rangabali: "রাঙ্গাবালী",
  Bhandaria: "ভান্ডারিয়া",
  Kaukhali: "কাউখালী",
  Mathbaria: "মঠবাড়িয়া",
  Nazirpur: "নাজিরপুর",
  "Pirojpur Sadar": "পিরোজপুর সদর",
  "Nesarabad (Swarupkathi)": "নেছারাবাদ (স্বরূপকাঠি)",

  // Chattogram division
  "Ali Kadam": "আলীকদম",
  "Bandarban Sadar": "বান্দরবান সদর",
  Lama: "লামা",
  Naikhongchhari: "নাইক্ষ্যংছড়ি",
  Rowangchhari: "রোয়াংছড়ি",
  Ruma: "রুমা",
  Thanchi: "থানচি",
  Akhaura: "আখাউড়া",
  Bancharampur: "বাঞ্ছারামপুর",
  "Brahmanbaria Sadar": "ব্রাহ্মণবাড়িয়া সদর",
  Kasba: "কসবা",
  Nabinagar: "নবীনগর",
  Nasirnagar: "নাসিরনগর",
  Sarail: "সরাইল",
  "Chandpur Sadar": "চাঁদপুর সদর",
  Faridganj: "ফরিদগঞ্জ",
  Haimchar: "হাইমচর",
  Haziganj: "হাজীগঞ্জ",
  Kachua: "কচুয়া",
  "Matlab Dakshin": "মতলব দক্ষিণ",
  "Matlab Uttar": "মতলব উত্তর",
  Shahrasti: "শাহরাস্তি",
  Anwara: "আনোয়ারা",
  Banshkhali: "বাঁশখালী",
  Boalkhali: "বোয়ালখালী",
  Chandanaish: "চন্দনাইশ",
  Fatikchhari: "ফটিকছড়ি",
  Hathazari: "হাটহাজারী",
  Karnafuli: "কর্ণফুলী",
  Lohagara: "লোহাগড়া",
  Mirsarai: "মীরসরাই",
  Patiya: "পটিয়া",
  Rangunia: "রাঙ্গুনিয়া",
  Raozan: "রাউজান",
  Sandwip: "সন্দ্বীপ",
  Satkania: "সাতকানিয়া",
  Sitakunda: "সীতাকুণ্ড",
  "Bayezid Bostami": "বায়েজিদ বোস্তামী",
  Chandgaon: "চান্দগাঁও",
  "Double Mooring": "ডবলমুরিং",
  Halishahar: "হালিশহর",
  Kotwali: "কোতোয়ালী",
  Pahartali: "পাহাড়তলী",
  Panchlaish: "পাঁচলাইশ",
  Patenga: "পতেঙ্গা",
  Chakaria: "চকরিয়া",
  "Cox's Bazar Sadar": "কক্সবাজার সদর",
  Kutubdia: "কুতুবদিয়া",
  Maheshkhali: "মহেশখালী",
  Ramu: "রামু",
  Teknaf: "টেকনাফ",
  Ukhia: "উখিয়া",
  Pekua: "পেকুয়া",
  Barura: "বরুড়া",
  Brahmanpara: "ব্রাহ্মণপাড়া",
  Burichang: "বুড়িচং",
  Chandina: "চান্দিনা",
  Chouddagram: "চৌদ্দগ্রাম",
  Daudkandi: "দাউদকান্দি",
  Debidwar: "দেবিদ্বার",
  Homna: "হোমনা",
  Laksam: "লাকসাম",
  Monohargonj: "মনোহরগঞ্জ",
  Meghna: "মেঘনা",
  Muradnagar: "মুরাদনগর",
  Nangalkot: "নাঙ্গলকোট",
  "Cumilla Adarsha Sadar": "কুমিল্লা আদর্শ সদর",
  Sadarsouth: "সদর দক্ষিণ",
  Titas: "তিতাস",
  Chhagalnaiya: "ছাগলনাইয়া",
  Daganbhuiyan: "দাগনভূঞা",
  "Feni Sadar": "ফেনী সদর",
  Parshuram: "পরশুরাম",
  Sonagazi: "সোনাগাজী",
  Dighinala: "দীঘিনালা",
  "Khagrachhari Sadar": "খাগড়াছড়ি সদর",
  Lakshmichhari: "লক্ষ্মীছড়ি",
  Mahalchhari: "মহালছড়ি",
  Manikchhari: "মানিকছড়ি",
  Matiranga: "মাটিরাঙ্গা",
  Panchhari: "পানছড়ি",
  Ramgarh: "রামগড়",
  Kamalnagar: "কমলনগর",
  "Lakshmipur Sadar": "লক্ষ্মীপুর সদর",
  Raipur: "রায়পুর",
  Ramganj: "রামগঞ্জ",
  Ramgati: "রামগতি",
  Begumganj: "বেগমগঞ্জ",
  Chatkhil: "চাটখিল",
  Companiganj: "কোম্পানীগঞ্জ",
  Hatiya: "হাতিয়া",
  Kabirhat: "কবিরহাট",
  "Noakhali Sadar": "নোয়াখালী সদর",
  Senbagh: "সেনবাগ",
  Sonaimuri: "সোনাইমুড়ী",
  Subarnachar: "সুবর্ণচর",
  Baghaichhari: "বাঘাইছড়ি",
  Barkal: "বরকল",
  Belaichhari: "বিলাইছড়ি",
  Juraichhari: "জুরাছড়ি",
  Kaptai: "কাপ্তাই",
  "Kawkhali (Rangamati)": "কাউখালী (রাঙামাটি)",
  Langadu: "লংগদু",
  Naniarchar: "নানিয়ারচর",
  Rajasthali: "রাজস্থলী",
  "Rangamati Sadar": "রাঙামাটি সদর",

  // Dhaka division
  Adabor: "আদাবর",
  Badda: "বাড্ডা",
  Bangshal: "বংশাল",
  Cantonment: "ক্যান্টনমেন্ট",
  Chakbazar: "চকবাজার",
  Dhanmondi: "ধানমন্ডি",
  Gendaria: "গেন্ডারিয়া",
  Gulshan: "গুলশান",
  Hazaribagh: "হাজারীবাগ",
  Jatrabari: "যাত্রাবাড়ী",
  Kafrul: "কাফরুল",
  Kalabagan: "কলাবাগান",
  Kamrangirchar: "কামরাঙ্গীরচর",
  Khilgaon: "খিলগাঁও",
  Khilkhet: "খিলক্ষেত",
  Lalbagh: "লালবাগ",
  Mirpur: "মিরপুর",
  Mohammadpur: "মোহাম্মদপুর",
  Motijheel: "মতিঝিল",
  "New Market": "নিউমার্কেট",
  Pallabi: "পল্লবী",
  Paltan: "পল্টন",
  Ramna: "রমনা",
  Rampura: "রামপুরা",
  Sabujbagh: "সবুজবাগ",
  "Shah Ali": "শাহ আলী",
  Shahbagh: "শাহবাগ",
  "Sher-e-Bangla Nagar": "শেরেবাংলা নগর",
  Shyampur: "শ্যামপুর",
  Sutrapur: "সূত্রাপুর",
  Tejgaon: "তেজগাঁও",
  "Tejgaon Industrial Area": "তেজগাঁও শিল্প এলাকা",
  Turag: "তুরাগ",
  Uttara: "উত্তরা",
  Vatara: "ভাটারা",
  Dhamrai: "ধামরাই",
  Dohar: "দোহার",
  Keraniganj: "কেরানীগঞ্জ",
  Nawabganj: "নবাবগঞ্জ",
  Savar: "সাভার",
  Alfadanga: "আলফাডাঙ্গা",
  Bhanga: "ভাঙ্গা",
  Boalmari: "বোয়ালমারী",
  Charbhadrashen: "চরভদ্রাসন",
  "Faridpur Sadar": "ফরিদপুর সদর",
  Madhukhali: "মধুখালী",
  Nagarkanda: "নগরকান্দা",
  Sadarpur: "সদরপুর",
  Saltha: "সালথা",
  "Gazipur Sadar": "গাজীপুর সদর",
  Kaliakair: "কালিয়াকৈর",
  Kaliganj: "কালীগঞ্জ",
  Kapasia: "কাপাসিয়া",
  Sreepur: "শ্রীপুর",
  "Tongi Sadar": "টঙ্গী সদর",
  "Gopalganj Sadar": "গোপালগঞ্জ সদর",
  Kashiani: "কাশিয়ানী",
  Kotalipara: "কোটালীপাড়া",
  Muksudpur: "মুকসুদপুর",
  Tungipara: "টুঙ্গিপাড়া",
  Austagram: "অষ্টগ্রাম",
  Bajitpur: "বাজিতপুর",
  Bhairab: "ভৈরব",
  Hossainpur: "হোসেনপুর",
  Itna: "ইটনা",
  Karimganj: "করিমগঞ্জ",
  Katiadi: "কটিয়াদী",
  "Kishoreganj Sadar": "কিশোরগঞ্জ সদর",
  Kuliarchar: "কুলিয়ারচর",
  Mithamain: "মিঠামইন",
  Nikli: "নিকলী",
  Pakundia: "পাকুন্দিয়া",
  Tarail: "তাড়াইল",
  Kalkini: "কালকিনি",
  "Madaripur Sadar": "মাদারীপুর সদর",
  Rajoir: "রাজৈর",
  Shibchar: "শিবচর",
  Daulatpur: "দৌলতপুর",
  Ghior: "ঘিওর",
  Harirampur: "হরিরামপুর",
  "Manikganj Sadar": "মানিকগঞ্জ সদর",
  Saturia: "সাটুরিয়া",
  Shivalaya: "শিবালয়",
  Singair: "সিংগাইর",
  Gazaria: "গজারিয়া",
  Lohajang: "লৌহজং",
  "Munshiganj Sadar": "মুন্সিগঞ্জ সদর",
  Sirajdikhan: "সিরাজদিখান",
  Sreenagar: "শ্রীনগর",
  Tongibari: "টংগীবাড়ী",
  "Narayanganj Sadar": "নারায়ণগঞ্জ সদর",
  Araihazar: "আড়াইহাজার",
  Bandar: "বন্দর",
  Rupganj: "রূপগঞ্জ",
  Sonargaon: "সোনারগাঁও",
  Belabo: "বেলাবো",
  Manohardi: "মনোহরদী",
  "Narsingdi Sadar": "নরসিংদী সদর",
  Palash: "পলাশ",
  Raipura: "রায়পুরা",
  Shibpur: "শিবপুর",
  Baliakandi: "বালিয়াকান্দি",
  Goalandaghat: "গোয়ালন্দ ঘাট",
  Kalukhali: "কালুখালী",
  Pangsha: "পাংশা",
  "Rajbari Sadar": "রাজবাড়ী সদর",
  Bhedarganj: "ভেদরগঞ্জ",
  Damudya: "ডামুড্যা",
  Gosairhat: "গোসাইরহাট",
  Jajira: "জাজিরা",
  Naria: "নড়িয়া",
  "Shariatpur Sadar": "শরীয়তপুর সদর",
  Zanjira: "জাঞ্জিরা",
  Basail: "বাসাইল",
  Bhuapur: "ভূঞাপুর",
  Delduar: "দেলদুয়ার",
  Dhanbari: "ধনবাড়ী",
  Ghatail: "ঘাটাইল",
  Gopalpur: "গোপালপুর",
  Kalihati: "কালিহাতী",
  Madhupur: "মধুপুর",
  Mirzapur: "মির্জাপুর",
  Nagarpur: "নাগরপুর",
  Sakhipur: "সখীপুর",
  "Tangail Sadar": "টাঙ্গাইল সদর",

  // Khulna division
  "Bagerhat Sadar": "বাগেরহাট সদর",
  Chitalmari: "চিতলমারী",
  Fakirhat: "ফকিরহাট",
  Mollahat: "মোল্লাহাট",
  Mongla: "মোংলা",
  Morrelganj: "মোড়েলগঞ্জ",
  Rampal: "রামপাল",
  Sarankhola: "শরণখোলা",
  Alamdanga: "আলমডাঙ্গা",
  "Chuadanga Sadar": "চুয়াডাঙ্গা সদর",
  Damurhuda: "দামুড়হুদা",
  Jibannagar: "জীবননগর",
  Abhaynagar: "অভয়নগর",
  Bagherpara: "বাঘারপাড়া",
  Chaugachha: "চৌগাছা",
  Jhikargachha: "ঝিকরগাছা",
  Keshabpur: "কেশবপুর",
  "Jashore Sadar": "যশোর সদর",
  Manirampur: "মণিরামপুর",
  Sharsha: "শার্শা",
  Harinakunda: "হরিণাকুণ্ডু",
  "Jhenaidah Sadar": "ঝিনাইদহ সদর",
  Kotchandpur: "কোটচাঁদপুর",
  Maheshpur: "মহেশপুর",
  Shailkupa: "শৈলকুপা",
  Batiaghata: "বটিয়াঘাটা",
  Dacope: "দাকোপ",
  Dumuria: "ডুমুরিয়া",
  Dighalia: "দিঘলিয়া",
  Koyra: "কয়রা",
  Paikgachha: "পাইকগাছা",
  Phultala: "ফুলতলা",
  Rupsha: "রূপসা",
  Terokhada: "তেরখাদা",
  Khalishpur: "খালিশপুর",
  "Khan Jahan Ali": "খানজাহান আলী",
  Sonadanga: "সোনাডাঙ্গা",
  Bheramara: "ভেড়ামারা",
  Kumarkhali: "কুমারখালী",
  "Kushtia Sadar": "কুষ্টিয়া সদর",
  Khoksa: "খোকসা",
  "Magura Sadar": "মাগুরা সদর",
  Shalikha: "শালিখা",
  Gangni: "গাংনী",
  "Meherpur Sadar": "মেহেরপুর সদর",
  Mujibnagar: "মুজিবনগর",
  Kalia: "কালিয়া",
  "Narail Sadar": "নড়াইল সদর",
  Assasuni: "আশাশুনি",
  Debhata: "দেবহাটা",
  Kalaroa: "কলারোয়া",
  "Satkhira Sadar": "সাতক্ষীরা সদর",
  Shyamnagar: "শ্যামনগর",
  Tala: "তালা",

  // Mymensingh division
  Baksiganj: "বকশীগঞ্জ",
  Dewanganj: "দেওয়ানগঞ্জ",
  Islampur: "ইসলামপুর",
  "Jamalpur Sadar": "জামালপুর সদর",
  Madarganj: "মাদারগঞ্জ",
  Melandaha: "মেলান্দহ",
  Sarishabari: "সরিষাবাড়ী",
  Bhaluka: "ভালুকা",
  Dhobaura: "ধোবাউড়া",
  Fulbaria: "ফুলবাড়িয়া",
  Gaffargaon: "গফরগাঁও",
  Gauripur: "গৌরীপুর",
  Haluaghat: "হালুয়াঘাট",
  Ishwarganj: "ঈশ্বরগঞ্জ",
  "Mymensingh Sadar": "ময়মনসিংহ সদর",
  Muktagachha: "মুক্তাগাছা",
  Nandail: "নান্দাইল",
  Phulpur: "ফুলপুর",
  Trishal: "ত্রিশাল",
  "Tara Khanda": "তারাকান্দা",
  Atpara: "আটপাড়া",
  Barhatta: "বারহাট্টা",
  Durgapur: "দুর্গাপুর",
  Khaliajuri: "খালিয়াজুরী",
  Kalmakanda: "কলমাকান্দা",
  " Kendua": "কেন্দুয়া",
  Madan: "মদন",
  Mohanganj: "মোহনগঞ্জ",
  "Netrokona Sadar": "নেত্রকোণা সদর",
  Purbadhala: "পূর্বধলা",
  Jhenaigati: "ঝিনাইগাতী",
  Nakla: "নকলা",
  Nalitabari: "নালিতাবাড়ী",
  "Sherpur Sadar": "শেরপুর সদর",
  Sreebardi: "শ্রীবরদী",

  // Rajshahi division
  Adamdighi: "আদমদীঘি",
  "Bogra Sadar": "বগুড়া সদর",
  Sherpur: "শেরপুর",
  Dhunat: "ধুনট",
  Dhupchanchia: "দুপচাঁচিয়া",
  Gabtali: "গাবতলী",
  Kahaloo: "কাহালু",
  Nandigram: "নন্দীগ্রাম",
  Sariakandi: "সারিয়াকান্দি",
  Shajahanpur: "শাজাহানপুর",
  Sonatola: "সোনাতলা",
  Shibganj: "শিবগঞ্জ",
  Akkelpur: "আক্কেলপুর",
  "Joypurhat Sadar": "জয়পুরহাট সদর",
  Kalai: "কালাই",
  Khetlal: "ক্ষেতলাল",
  Panchbibi: "পাঁচবিবি",
  Atrai: "আত্রাই",
  Badalgachhi: "বদলগাছী",
  Dhamoirhat: "ধামইরহাট",
  Manda: "মান্দা",
  Mohadevpur: "মহাদেবপুর",
  "Naogaon Sadar": "নওগাঁ সদর",
  Niamatpur: "নিয়ামতপুর",
  Patnitala: "পত্নীতলা",
  Porsha: "পোরশা",
  Raninagar: "রাণীনগর",
  Sapahar: "সাপাহার",
  Bagatipara: "বাগাতিপাড়া",
  Baraigram: "বড়াইগ্রাম",
  Gurudaspur: "গুরুদাসপুর",
  Lalpur: "লালপুর",
  "Natore Sadar": "নাটোর সদর",
  Singra: "সিংড়া",
  Bholahat: "ভোলাহাট",
  Gomastapur: "গোমস্তাপুর",
  Nachole: "নাচোল",
  "Nawabganj Sadar": "চাঁপাইনবাবগঞ্জ সদর",
  Atgharia: "আটঘরিয়া",
  Bera: "বেড়া",
  Bhangura: "ভাঙ্গুড়া",
  Chatmohar: "চাটমোহর",
  Faridpur: "ফরিদপুর",
  Ishwardi: "ঈশ্বরদী",
  "Pabna Sadar": "পাবনা সদর",
  Santhia: "সাঁথিয়া",
  Sujanagar: "সুজানগর",
  Bagha: "বাঘা",
  Bagmara: "বাগমারা",
  Charghat: "চারঘাট",
  Godagari: "গোদাগাড়ী",
  Mohanpur: "মোহনপুর",
  Paba: "পবা",
  Puthia: "পুঠিয়া",
  Tanore: "তানোর",
  Boalia: "বোয়ালিয়া",
  Rajpara: "রাজপাড়া",
  "Shah Mokdum": "শাহ মখদুম",
  Motihar: "মতিহার",
  Belkuchi: "বেলকুচি",
  Chauhali: "চৌহালী",
  Kamarkhanda: "কামারখন্দ",
  Kazipur: "কাজীপুর",
  Rayganj: "রায়গঞ্জ",
  Shahjadpur: "শাহজাদপুর",
  "Sirajganj Sadar": "সিরাজগঞ্জ সদর",
  Tarash: "তাড়াশ",
  Ullapara: "উল্লাপাড়া",

  // Rangpur division
  "Dinajpur Sadar": "দিনাজপুর সদর",
  Birganj: "বীরগঞ্জ",
  Bochaganj: "বোচাগঞ্জ",
  Chirirbandar: "চিরিরবন্দর",
  Phulbari: "ফুলবাড়ী",
  Ghoraghat: "ঘোড়াঘাট",
  Hakimpur: "হাকিমপুর",
  Kaharole: "কাহারোল",
  Khansama: "খানসামা",
  Parbatipur: "পার্বতীপুর",
  "Gaibandha Sadar": "গাইবান্ধা সদর",
  Fulchhari: "ফুলছড়ি",
  Gobindaganj: "গোবিন্দগঞ্জ",
  Palashbari: "পলাশবাড়ী",
  Saghata: "সাঘাটা",
  Sundarganj: "সুন্দরগঞ্জ",
  "Kurigram Sadar": "কুড়িগ্রাম সদর",
  Bhurungamari: "ভুরুঙ্গামারী",
  "Char Rajibpur": "চর রাজিবপুর",
  Chilmari: "চিলমারী",
  Nageshwari: "নাগেশ্বরী",
  Rajarhat: "রাজারহাট",
  Raomari: "রৌমারী",
  Ulipur: "উলিপুর",
  "Lalmonirhat Sadar": "লালমনিরহাট সদর",
  Aditmari: "আদিতমারী",
  Hatibandha: "হাতীবান্ধা",
  Patgram: "পাটগ্রাম",
  "Nilphamari Sadar": "নীলফামারী সদর",
  Dimla: "ডিমলা",
  Domar: "ডোমার",
  Jaldhaka: "জলঢাকা",
  Kishoreganj: "কিশোরগঞ্জ",
  Saidpur: "সৈয়দপুর",
  "Panchagarh Sadar": "পঞ্চগড় সদর",
  Atwari: "আটোয়ারী",
  Boda: "বোদা",
  Debiganj: "দেবীগঞ্জ",
  Tetulia: "তেঁতুলিয়া",
  "Rangpur Sadar": "রংপুর সদর",
  Badarganj: "বদরগঞ্জ",
  Gangachara: "গংগাচড়া",
  Kaunia: "কাউনিয়া",
  Mithapukur: "মিঠাপুকুর",
  Pirgacha: "পীরগাছা",
  Pirganj: "পীরগঞ্জ",
  Taraganj: "তারাগঞ্জ",
  "Thakurgaon Sadar": "ঠাকুরগাঁও সদর",
  Baliadangi: "বালিয়াডাঙ্গী",
  Haripur: "হরিপুর",
  Ranisankail: "রাণীশংকৈল",

  // Sylhet division
  Ajmiriganj: "আজমিরীগঞ্জ",
  Bahubal: "বাহুবল",
  Baniachong: "বানিয়াচং",
  Chunarughat: "চুনারুঘাট",
  "Habiganj Sadar": "হবিগঞ্জ সদর",
  Lakhai: "লাখাই",
  Madhabpur: "মাধবপুর",
  Nabiganj: "নবীগঞ্জ",
  Barlekha: "বড়লেখা",
  Juri: "জুড়ী",
  Kamalganj: "কমলগঞ্জ",
  Kulaura: "কুলাউড়া",
  "Moulvibazar Sadar": "মৌলভীবাজার সদর",
  Rajnagar: "রাজনগর",
  Sreemangal: "শ্রীমঙ্গল",
  Bishwamvarpur: "বিশ্বম্ভরপুর",
  Chhatak: "ছাতক",
  "Dakshin Sunamganj": "দক্ষিণ সুনামগঞ্জ",
  Derai: "দিরাই",
  Dharampasha: "ধরমপাশা",
  Dowarabazar: "দোয়ারাবাজার",
  Jagannathpur: "জগন্নাথপুর",
  Jamalganj: "জামালগঞ্জ",
  Shalla: "শাল্লা",
  "Sunamganj Sadar": "সুনামগঞ্জ সদর",
  Tahirpur: "তাহিরপুর",
  Balaganj: "বালাগঞ্জ",
  Beanibazar: "বিয়ানীবাজার",
  Bishwanath: "বিশ্বনাথ",
  Fenchuganj: "ফেঞ্চুগঞ্জ",
  Golapganj: "গোলাপগঞ্জ",
  Gowainghat: "গোয়াইনঘাট",
  Jaintiapur: "জৈন্তাপুর",
  Kanaighat: "কানাইঘাট",
  Osmaninagar: "ওসমানীনগর",
  "Sylhet Sadar": "সিলেট সদর",
  Zakiganj: "জকিগঞ্জ",
};

// ============================================================
// 4. REVERSE MAPS (Bangla → English) for API lookups
// ============================================================
export const divisionBnToEn: Record<string, string> = {};
export const districtBnToEn: Record<string, string> = {};
export const thanaBnToEn: Record<string, string> = {};

for (const [en, bn] of Object.entries(divisionBn)) {
  divisionBnToEn[bn] = en;
}
for (const [en, bn] of Object.entries(districtBn)) {
  districtBnToEn[bn] = en;
}
for (const [en, bn] of Object.entries(thanaBn)) {
  thanaBnToEn[bn] = en;
}

// ============================================================
// 5. BUILD BANGLA LISTS (using the translation maps above)
// ============================================================
export const divisionList = divisionListEn.map((en) => divisionBn[en] || en);

export const districtByDivision: Record<string, string[]> = {};
for (const [divEn, districtsEn] of Object.entries(districtByDivisionEn)) {
  const divBn = divisionBn[divEn] || divEn;
  districtByDivision[divBn] = districtsEn.map((en) => districtBn[en] || en);
}

export const thanaByDistrict: Record<string, string[]> = {};
for (const [distEn, thanasEn] of Object.entries(thanaByDistrictEn)) {
  const distBn = districtBn[distEn] || distEn;
  thanaByDistrict[distBn] = thanasEn.map((en) => thanaBn[en] || en);
}

// ============================================================
// 6. KHADEM PER DISTRICT (64 districts)
// ============================================================
export const khademByDistrict: Record<string, string> = {};
for (const district of Object.keys(districtBn)) {
  // Use the Bangla name as key, and set a placeholder name.
  // Replace these with actual names as needed.
  khademByDistrict[districtBn[district]] = `খাদেম - ${districtBn[district]}`;
}

// ============================================================
// 7. COORDINATOR PER DIVISION (8 divisions)
// ============================================================
export const coordinatorByDivision: Record<string, string> = {};
for (const division of Object.keys(divisionBn)) {
  coordinatorByDivision[divisionBn[division]] = `সমন্বয়ক - ${divisionBn[division]}`;
}

// ============================================================
// 8. PO BY UNION (currently empty – you can fill this later)
//    Since the form uses a text input for PO, this is optional.
// ============================================================
export const poByUnion: Record<string, string[]> = {};